#+Title: Documentation on Installation of Supybot 
#+Author: Sravanthi. M
#+Date: 04-09-2017

* Introduction
  This document contains the installation and configuration of Supybot for IRC channel to log the messages.
* Supybot
  Supybot is a robust (it doesn't crash), user friendly (it's easy to
  configure) and programmer friendly (plugins are extremely easy to
  write) Python IRC bot. 
* Installation of Supybot
** Steps to create a container and add a user 
  - Create a container on base4 with below command:
    #+BEGIN_EXAMPLE
    vzctl create CTID --ostemplate ubuntu-14.04-x86_64 --ipadd 10.4.12.24 --hostname Duplicate-IRC-channel.vlabs.ac.in 
    #+END_EXAMPLE
  - Then start the container as:
    #+BEGIN_EXAMPLE
    vzctl start CTID
    #+END_EXAMPLE
  - Enter into the container as :
    #+BEGIN_EXAMPLE
    vzctl enter CTID
    #+END_EXAMPLE
  - Add user to the container as
    #+BEGIN_EXAMPLE
    useradd -m username
    #+END_EXAMPLE
  - Switch to the user as : 
    #+BEGIN_EXAMPLE
    sudo su - username
    #+END_EXAMPLE
** Steps to install Supybot
   - Set proxyto install supybot with the below commanda:
     #+BEGIN_EXAMPLE 
     export http_proxy="http://proxy.iiit.ac.in:8080"
     export https_proxy="http://proxy.iiit.ac.in:8080"
    #+END_EXAMPLE
   - Update te packages to using below command
     #+BEGIN_EXAMPLE 
     sudo apt-get update
     #+END_EXAMPLE 
   - Command to install supybot
     #+BEGIN_EXAMPLE 
     sudo apt-get install supybot
     #+END_EXAMPLE 
   - create a folder named supybot in home directory
     #+BEGIN_EXAMPLE
     cd ~
     mkdir supybot
     cd supybot
     supybot-wizard
     #+END_EXAMPLE
** Configure the Supybot-wizard
   - Supytbot-wizard is to setup network, server, bot nickname, logs, plugins etc.,.
   - A file is created with  <bot-name>.conf after the configuration.
     #+BEGIN_EXAMPLE 
     supybot <configurationfile>.conf
     #+END_EXAMPLE
   - This programme will connect you to the configured IRC
     channels. And now you are able to see the bot logged into
     the IRC channel with botname that you specified during
     configuration. (Check once by log into the IRC channel) 
   - If you could see bot logged into the specified IRC channles that
     means you are succesfully configured bot for your channels.
